# General Settings
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix
set -sg escape-time 10

set -g default-shell /home/eagle/.nix-profile/bin/zsh

# Window and Pane Indexing
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Key Bindings for Pane Management
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Key Bindings for Pane Navigation
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind h select-pane -L

# Key Bindings for Pane Resizing
bind Down resize-pane -D 5
bind Up resize-pane -U 5
bind Right resize-pane -R 5
bind Left resize-pane -L 5

# Session Navigation
bind-key P switch-client -p
bind-key N switch-client -n

# Mouse and Clipboard Settings
set -g set-clipboard on
set -g mouse on
set-window-option -g mode-keys vi

# Copy Mode Key Bindings
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane

# Reload Configuration
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# TPM (Tmux Plugin Manager) and Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-weather'

set -g @weather_location 'Hanoi, VN'
set -g @theme_transparent_status_bar 'true'

# Plugin Settings
set -g @sessionx-custom-paths \
  '01Gen, 02Config, 03Chat'
  # 01Code,02Note,03Config,04Look,05Chat'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-save-interval '0'  # Disable auto-save
# set -g @continuum-restore 'on'

# Initialize TPM (Keep this line at the very bottom)
# run '~/.config/tmux/plugins/tpm/tpm'
run '~/dotfiles/tmux/plugins/tpm/tpm'

# prefix [: enter copy mode
# prefix I: Install session
# prefix r: Reload Tmux config
# prefix s: liSt sessions
# prefix C-s: Save session
# prefix C-r: Restore session
# prefix D: Detach session
# prefix &: kill current session
# prefix $: rename session
# prefix N/): Next session
# prefix P/(: Previous session
# prefix c: Create new window
# prefix ,: Rename window
# prefix n: Next window
# prefix p: Previous window
# prefix number: switch window by number
# prefix z: toggle pane Zoom
# prefix x: close pane
# ref: https://defkey.com/tmux-shortcuts
